build:
  noJSConfigInAssets: true
  writeStats: true
copyright: 2022
disableKinds:
  - "RSS"
  - "taxonomy"
  - "term"
enableEmoji: true
enableRobotsTXT: true
imaging:
  exif:
    disableDate: true
    disableLatLong: true
  quality: 85
languageCode: "en-us"
paginate: 20
params:
  logo: "logo.svg"
  slogan: "Custom marine canvas and upholstery"
  defaults:
    ctas:
      default:
        path: "simple.html"
      simple:
        text: "Get in touch to start a project!"
        subText:
        label: "Contact"
        link: "/contact"
      winter:
        text: "Booking winter projects!"
        subText:
        label: "Reserve"
        link: "/contact"
        snowflakeCount: 250
      splashDay:
        text: "Is your boat ready for splash day?"
        subText:
        label: "Contact"
        link: "/contact"
    featuredImage:
      default:
        path: "default-featured-image.png"
      linkToOriginal:
        list: true
        section: true
        single: true
pluralizeListTitles: true
relativeURLs: true
sitemap:
  changefreq: "weekly"
timeZone: "America/New_York"
