version: "3.7"

services:
  https:
    image: steveltn/https-portal:1
    container_name: https_proxy
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      - DOMAINS
      - STAGE
      - CLIENT_MAX_BODY_SIZE

  db:
    image: mariadb
    container_name: mysql
    command: mysqld --max-allowed-packet=256M
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

  app:
    image: jbboynton/wp_docker_base:latest
    container_name: app
    restart: always
    volumes:
      - /app:/var/www/app
      - /config:/var/www/config
      - /vendor:/var/www/vendor
      - /ops/.env_app:/var/www/config/.env
    environment:
      - SITE_NAME
      - WP_ENV

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - '8888:80'
    restart: always
    environment:
      - PMA_HOST
      - PMA_USER
      - PMA_PASSWORD
      - MYSQL_PASSWORD

volumes:
  data:
