Vagrant.configure("2") do |config|
  config.vm.box = "Knowy/Ubuntu-Trusty64-Docker"
  config.vm.box_version = "1.8"

  config.vm.network "private_network", ip: "192.168.50.2"
  config.vm.network :forwarded_port,
    guest: 22,
    host: 2208,
    id: "ssh",
    auto_correct: true

  config.vm.hostname = "bcmarinecanvasri.local"
  config.hostsupdater.aliases = ["www.bcmarinecanvasri.local"]
  config.hostsupdater.remove_on_suspend = false

  config.ssh.forward_agent = true

  config.timezone.value = "America/New_York"

  config.vm.synced_folder "../app", "/app",
    owner: "www-data",
    group: "www-data",
    mount_options: ["dmode=777", "fmode=777"]

  config.vm.synced_folder "../config", "/config",
    owner: "www-data",
    group: "www-data",
    mount_options: ["dmode=777", "fmode=777"]

  config.vm.synced_folder "../dump", "/dump",
    mount_options: ["dmode=777", "fmode=777"]

  config.vm.synced_folder "../ops", "/ops",
    mount_options: ["dmode=777", "fmode=777"]

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.synced_folder "../vendor", "/vendor",
    owner: "www-data",
    group: "www-data",
    mount_options: ["dmode=777", "fmode=777"]

  config.vm.provider :virtualbox do |vb|
    vb.customize [
      "modifyvm", :id,
      "--name", "bc_marine_canvas",
      "--memory", 3072,
      "--cpus", 2
    ]
  end

  config.vm.provision "shell",
    privileged: false,
    run: "always",
    inline: "cd /ops && make clean && make run"
end

# vim:ft=ruby
